Resources:
  VocoderBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cihackathon-vocoder-outputs
      
  VocoderBucketAllowPublicReadPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref VocoderBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Action: 
              - "s3:GetObject"
            Resource: 
              - !Join ['/', [!Ref VocoderBucket, 'public']]
            Principal: "*"

# Print out the name of the bucket that is created
Outputs:
  VocoderBucketName:
    Value:
      Ref: VocoderBucket
